"""Remove project_type_id from projects table

Revision ID: 90a10d1ca994
Revises: 011_add_division_to_users
Create Date: 2026-02-10 12:56:29.144894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '90a10d1ca994'
down_revision: Union[str, None] = '011_add_division_to_users'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove project_type_id foreign key constraint and column from projects table
    op.drop_constraint('projects_project_type_id_fkey', 'projects', type_='foreignkey')
    op.drop_column('projects', 'project_type_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Restore project_type_id column and foreign key constraint
    op.add_column('projects', sa.Column('project_type_id', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.create_foreign_key('projects_project_type_id_fkey', 'projects', 'project_types', ['project_type_id'], ['id'])
    # ### end Alembic commands ###
