"""
Standardized error codes and helper for consistent API error responses.
All error responses follow the format: {"code": "ERROR_CODE", "message": "Human-readable message"}
"""

from fastapi import HTTPException


class ErrorCode:
    # Auth (AUTH_*)
    AUTH_INVALID_CREDENTIALS = "AUTH_INVALID_CREDENTIALS"
    AUTH_INACTIVE_USER = "AUTH_INACTIVE_USER"
    AUTH_INSUFFICIENT_PERMISSIONS = "AUTH_INSUFFICIENT_PERMISSIONS"
    AUTH_READ_ONLY = "AUTH_READ_ONLY"
    AUTH_INVALID_TOKEN = "AUTH_INVALID_TOKEN"
    AUTH_EXPIRED_TOKEN = "AUTH_EXPIRED_TOKEN"
    AUTH_INVALID_REFRESH_TOKEN = "AUTH_INVALID_REFRESH_TOKEN"
    AUTH_SSO_DISABLED = "AUTH_SSO_DISABLED"
    AUTH_SAML_FAILED = "AUTH_SAML_FAILED"
    AUTH_REGISTRATION_TOKEN_INVALID = "AUTH_REGISTRATION_TOKEN_INVALID"
    AUTH_DUPLICATE_EMAIL = "AUTH_DUPLICATE_EMAIL"

    # Password
    AUTH_WRONG_PASSWORD = "AUTH_WRONG_PASSWORD"
    AUTH_PASSWORD_TOO_SHORT = "AUTH_PASSWORD_TOO_SHORT"
    AUTH_PASSWORD_PERSIST_FAILED = "AUTH_PASSWORD_PERSIST_FAILED"

    # Not Found (NOT_FOUND_*)
    NOT_FOUND_USER = "NOT_FOUND_USER"
    NOT_FOUND_PROJECT = "NOT_FOUND_PROJECT"
    NOT_FOUND_WORKLOG = "NOT_FOUND_WORKLOG"
    NOT_FOUND_RESOURCE_PLAN = "NOT_FOUND_RESOURCE_PLAN"
    NOT_FOUND_DEPARTMENT = "NOT_FOUND_DEPARTMENT"
    NOT_FOUND_DIVISION = "NOT_FOUND_DIVISION"
    NOT_FOUND_BUSINESS_UNIT = "NOT_FOUND_BUSINESS_UNIT"
    NOT_FOUND_SUB_TEAM = "NOT_FOUND_SUB_TEAM"
    NOT_FOUND_JOB_POSITION = "NOT_FOUND_JOB_POSITION"
    NOT_FOUND_PROJECT_ROLE = "NOT_FOUND_PROJECT_ROLE"
    NOT_FOUND_MILESTONE = "NOT_FOUND_MILESTONE"
    NOT_FOUND_SCENARIO = "NOT_FOUND_SCENARIO"
    NOT_FOUND_HIRING_PLAN = "NOT_FOUND_HIRING_PLAN"
    NOT_FOUND_INTERNAL_IO = "NOT_FOUND_INTERNAL_IO"
    NOT_FOUND_RECHARGE_IO = "NOT_FOUND_RECHARGE_IO"
    NOT_FOUND_WORK_TYPE = "NOT_FOUND_WORK_TYPE"
    NOT_FOUND_PRODUCT_LINE = "NOT_FOUND_PRODUCT_LINE"
    NOT_FOUND_HISTORY = "NOT_FOUND_HISTORY"

    # Duplicate/Conflict (DUPLICATE_*)
    DUPLICATE_EMAIL = "DUPLICATE_EMAIL"
    DUPLICATE_CODE = "DUPLICATE_CODE"
    DUPLICATE_NAME = "DUPLICATE_NAME"
    DUPLICATE_IO = "DUPLICATE_IO"

    # Validation (VALIDATION_*)
    VALIDATION_HOURS_EXCEED = "VALIDATION_HOURS_EXCEED"
    VALIDATION_INVALID_DEPARTMENT = "VALIDATION_INVALID_DEPARTMENT"
    VALIDATION_INVALID_POSITION = "VALIDATION_INVALID_POSITION"
    VALIDATION_FAILED = "VALIDATION_FAILED"
    VALIDATION_MILESTONE_MISMATCH = "VALIDATION_MILESTONE_MISMATCH"

    # Dependency (DEPENDENCY_*)
    DEPENDENCY_HAS_USERS = "DEPENDENCY_HAS_USERS"
    DEPENDENCY_HAS_DEPARTMENTS = "DEPENDENCY_HAS_DEPARTMENTS"
    DEPENDENCY_HAS_SUB_TEAMS = "DEPENDENCY_HAS_SUB_TEAMS"
    DEPENDENCY_HAS_PROJECTS = "DEPENDENCY_HAS_PROJECTS"

    # Server
    SERVER_INTERNAL_ERROR = "SERVER_INTERNAL_ERROR"
    SERVER_AI_PARSE_ERROR = "SERVER_AI_PARSE_ERROR"


def app_error(
    status_code: int,
    code: str,
    detail: str,
    **kwargs,
) -> HTTPException:
    """Create HTTPException with error code in detail dict."""
    return HTTPException(
        status_code=status_code,
        detail={"code": code, "message": detail, **kwargs},
    )
